educportal/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy, include
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from educportal.views import SignUpView, SectionListView, ThemeListView, \
                                        PostTestListView, PostDetailView, ChangeUserInfoView, \
                                        TaskListView
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView,PasswordChangeDoneView




urlpatterns = [
    path(r'', TemplateView.as_view(template_name="educportal/home_page.html"), name = 'home_page'),
    path(r'register/', SignUpView.as_view(), name = 'reg_page'),
    path(r'login/',    LoginView.as_view(template_name='educportal/login.html'), name = 'login_page'),
    path(r'logout/',   LogoutView.as_view(), name = 'logout'),
    path(r'profile/',  login_required(TemplateView.as_view(template_name='educportal/profile_page.html'), login_url=reverse_lazy('login_page')), name = 'profile_page'),
    path(r'profile/personal_info',  login_required(TemplateView.as_view(template_name='educportal/personal_info.html'),login_url=reverse_lazy('login_page')), name = 'personal_info'),
    path(r'profile/change_personal_info', login_required(ChangeUserInfoView.as_view(), login_url=reverse_lazy('login_page') ), name = 'change_personal_info'),
    path(r'profile/change_personal_info/password_change/', login_required(PasswordChangeView.as_view(template_name='educportal/change_user_password.html', success_url=reverse_lazy('change_user_password_done')), login_url=reverse_lazy('login_page')), name = 'change_user_password'),
    path(r'profile/change_personal_info/password_change/done', login_required(PasswordChangeDoneView.as_view(template_name='educportal/personal_info.html'),login_url=reverse_lazy('login_page')), name = 'change_user_password_done'),
    path(r'degrees/<int:pk>/', SectionListView.as_view(), name='section_page'),
    path(r'degrees/<int:supersection_id>/<int:section_id>/themes', ThemeListView.as_view(),name = 'theme_list'),
    path(r'degrees/<int:supersection_id>/<int:section_id>/themes/<int:item_id>/post/', PostTestListView.as_view(),name = 'post_list'),
    path(r'degrees/<int:supersection_id>/<int:section_id>/themes/<int:item_id>/post/<int:post_item>', PostDetailView.as_view(), name = 'post_detail'),
    path(r'degrees/<int:supersection_id>/<int:section_id>/themes/<int:item_id>/test/<int:test_id>', TaskListView.as_view(), name = 'task_list'),
    path(r'i18n/', include('django.conf.urls.i18n')),
]

urfuwebapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
	path(r'', include('educportal.urls')),
	path(r'summernote/', include('django_summernote.urls')),
]

educportal/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext


class SuperSection (models.Model):

    name = models.CharField(max_length=10, unique=True, verbose_name=ugettext("Название супер раздела"))

    def __str__(self):
        return u"%s" % self.name

    class Meta:
        verbose_name = "Супер раздел"
        verbose_name_plural = "Супер разделы"


class GroupAccess(models.Model):
    level_access = models.PositiveSmallIntegerField()
    degree = models.CharField(max_length=10, blank=False, null=False, unique=True)

    def __str__(self):
        return u"%s" % self.degree

    class Meta:
        verbose_name = "Уровень доступа группы"
        verbose_name_plural = "Уровень доступа групп"


class AcademicGroup(models.Model):

    group_name = models.CharField(max_length=15,unique=True, verbose_name=ugettext("Название_группы"))
    group_access = models.ForeignKey(GroupAccess, on_delete=models.CASCADE)

    def __str__(self):
        return u"%s" % self.group_name

    class Meta:
        verbose_name = "Академическая группа"
        verbose_name_plural = "Академические группы"


class Section(models.Model):

    name = models.CharField(max_length=200, verbose_name=ugettext("Название дисциплины"))
    is_guest = models.BooleanField(default=False)
    access_section = models.ForeignKey(GroupAccess, on_delete=models.CASCADE)
    super_section = models.ForeignKey(SuperSection, on_delete=models.CASCADE)

    @property
    def level_access(self):
        return self.access_section.level_access

    def get_absolute_url(self):
        return reverse(
            'theme_list',
            kwargs={
                'supersection_id': self.super_section.pk,
                'section_id': self.pk
            }
        )


    def __str__(self):
        return u"%s" % self.name
    class Meta:

        verbose_name = ugettext("Дисциплина")
        verbose_name_plural = ugettext("Дисциплины")

class Theme(models.Model):

    name = models.CharField(max_length=200, verbose_name="Название темы")
    created_date = models.DateTimeField(default=timezone.now)
    discipline = models.ForeignKey(Section, on_delete=models.CASCADE)

    def __str__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse(
            'post_list',
            kwargs={
                'supersection_id': self.discipline.super_section.pk,
                'section_id': self.discipline.pk,
                'item_id':self.pk,
            }
        )

    class Meta:
        verbose_name = "Тема дисциплины"
        verbose_name_plural = "Темы дисциплин"

class Post(models.Model):

    title = models.CharField(max_length=200, verbose_name="Название поста")
    url_to_videopost = models.CharField(max_length=200, unique=True, blank=True, verbose_name="Ссылка на видеоролик", null=True)
    content = models.TextField(null=True, blank=True, verbose_name='Содержимое поста')
    post_type = models.BooleanField(default=True, null=False, verbose_name='Тип поста. 1-пост, 0-видеопост')
    created_date = models.DateTimeField(default=timezone.now)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse(
            'post_detail',
            kwargs={
                'supersection_id': self.theme.discipline.super_section.pk,
                'section_id': self.theme.discipline.pk,
                'item_id':self.theme.pk,
                'post_item': self.pk,
            }
        )

    def __str__(self):
        return u"%s" % self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"


class Test(models.Model):
    name = models.CharField(max_length=200, verbose_name="Название теста", null = False)
    theme = models.ForeignKey(Theme,on_delete=models.CASCADE, null = False)
    allowable_number_errors = models.PositiveSmallIntegerField(verbose_name='Допустимое количество ошибок', default=1)
    created_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse(
            'task_list',
            kwargs={
                'supersection_id': self.theme.discipline.super_section.pk,
                'section_id': self.theme.discipline.pk,
                'item_id':self.theme.pk,
                'test_id':self.pk,
            }
        )

    class Meta:
        verbose_name = "Тест"
        verbose_name_plural = "Тесты"



class Task(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок задания", null=False)
    task_content = models.TextField(verbose_name='Текст задания', null=False)
    serial_number = models.PositiveSmallIntegerField(verbose_name='Порядковый номер задания')
    test = models.ForeignKey(Test, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return u"%s" % self.title

    class Meta:
        verbose_name = "Задание"
        verbose_name_plural = "Задания"


# class Student(models.Model):
#     academic_group = models.ForeignKey(AcademicGroup, on_delete=models.CASCADE)
#
#     class Meta:
#         verbose_name = "Студент"
#         verbose_name_plural = "Студенты"

# class Department(models.Model):
#     name = models.CharField(max_length=200, verbose_name="Название департамента", null=False)
#
#     def __str__(self):
#         return '%s' % self.name
#
#     class Meta:
#         verbose_name = "Департамент"
#         verbose_name_plural = "Департаменты"

# class Teacher(models.Model):
#     department = models.ForeignKey(Department, on_delete=models.CASCADE, null=False)
#
#     class Meta:
#         verbose_name = "Преподаватель"
#         verbose_name_plural = "Преподаватели"

class TaskAnswer(models.Model):
    task_answer_content = models.TextField(verbose_name="Текст ответа", null=False)
    is_correct = models.BooleanField(default=False, verbose_name='Корректность ответа')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return '%s %d' % (self.task.title, self.pk)

    class Meta:
        verbose_name = "Ответ на задание"
        verbose_name_plural = "Ответы на задания"

class User(AbstractUser):
    email = models.EmailField(verbose_name='Email', unique=True)
    phone_number = PhoneNumberField(verbose_name='Телефон', blank = True,null = True)
    academic_group = models.ForeignKey(AcademicGroup, on_delete=models.CASCADE, null=True)

    @property
    def level_access(self):
        return self.academic_group.group_access.level_access

    @property
    def degree_student(self):
        return self.academic_group.group_access.degree

    @property
    def academ_group_student(self):
        return self.academic_group.group_name

# Create your models here.

educportal/forms.py
from django import forms
from django.forms import ModelForm
from educportal.models import User
from educportal.models import AcademicGroup
from django.utils.translation import  ugettext

class SignUpForm(ModelForm):
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')
    confirm_password = forms.CharField(
        label='Подтвердите пароль',
        widget=forms.PasswordInput(),
        strip=False
    )
    academic_group = forms.ModelChoiceField(queryset=AcademicGroup.objects.all(),required=True)

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username__iexact=username).exists():
            self.add_error('username', ugettext('Пользователь с таким именем уже существует!'))

        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email__iexact=email).exists():
            self.add_error('email', ugettext('Пользователь с таким email уже существует!'))

        return email.lower()

    def clean (self):
        super().clean()
        if 'password' in self.cleaned_data and 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                self.add_error(None, ugettext("Пароли должны совпадать!!!"))
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email','academic_group', 'password','phone_number')

educportal/views.py
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.urls import reverse_lazy
from django.views.generic import CreateView,TemplateView, ListView, DetailView, UpdateView
from django.views.generic.list import MultipleObjectMixin

from educportal.forms import SignUpForm
from educportal.models import User, Section, Post, Theme, Test,Task



# Create your views here.


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "educportal/register.html"
    success_url = reverse_lazy('login_page')


class SectionListView(TemplateView):
    template_name = 'educportal/section_list.html'

    def sections(self, is_guest = None):
        return Section.objects.filter(super_section__pk=self.kwargs['pk'], is_guest=is_guest)

    def get_context_data(self, **kwargs):
        context = super(SectionListView, self).get_context_data(**kwargs)
        context['section_guest'] = self.sections(is_guest=True)
        context['section'] = self.sections(is_guest=False)
        return context


class ThemeListView(ListView):
    template_name = "educportal/themes_list.html"
    context_object_name = "themes_list"

    def sections(self, is_guest=None):
        # return  Section.objects.filter(super_section__pk=self.kwargs['supersection_id'], is_guest=is_guest)
        return Section.objects.filter(super_section__section__pk=self.kwargs['section_id'], is_guest=is_guest)

    def get_context_data(self, **kwargs):
        context = super(ThemeListView, self).get_context_data(**kwargs)
        context['section_guest'] = self.sections(is_guest=True)
        context['section'] = self.sections(is_guest=False)
        return context

    def get_queryset(self):
        return Theme.objects.filter(discipline__pk=self.kwargs['section_id']).order_by('created_date')


class PostTestListView(ListView):
    template_name = 'educportal/post_test_list.html'
    context_object_name = 'post_list'
    model = Test

    def get_test(self):
        return self.model.objects.filter(theme__pk=self.kwargs['item_id']).order_by('created_date')

    # def get_task_first(self):
    #     return Task.objects.filter(test__theme__pk=self.kwargs['item_id']).order_by('serial_number').first();

    def get_context_data(self, **kwargs):
        context = super(PostTestListView,self).get_context_data(**kwargs)
        context['test_list'] = self.get_test()
        # context['task_item'] = self.get_task_first()
        return context

    def get_queryset(self):
        return Post.objects.filter(theme__pk=self.kwargs['item_id']).order_by('created_date')

class PostDetailView(DetailView):
    template_name = 'educportal/post_detail.html'
    pk_url_kwarg = "post_item"

    def get_test(self):
        return Test.objects.filter(theme__pk=self.kwargs['item_id']).order_by('created_date')

    def get_context_data(self, **kwargs):
        context = super(PostDetailView,self).get_context_data(**kwargs)
        context ['post_list'] = self.get_queryset()
        context['test_list'] = self.get_test()
        return context

    def get_queryset(self):
        return Post.objects.filter(theme__pk=self.kwargs['item_id']).order_by('created_date')

    def dispatch(self, request, *args, **kwargs):     # проверка прав пользователя. Если прав недостаточно,то уведомить об этом,
                                                        # иначе предоставить доступ к запрашиваемой информации
        section_object = Section.objects.get(pk=self.kwargs['section_id'])
        if(request.user.is_anonymous and not section_object.is_guest):
            # return HttpResponseRedirect((reverse_lazy('home_page')))
            return HttpResponseForbidden()
        elif(request.user.is_authenticated):
            if(request.user.level_access<section_object.level_access and not section_object.is_guest):
                return HttpResponseForbidden()
            else:
                return super(PostDetailView, self).dispatch(request)
        else:
            return super(PostDetailView,self).dispatch(request)



class TaskListView (ListView):
    template_name = 'educportal/task_item.html'
    context_object_name = 'task'
    model = Task
    paginate_by = 1
    def get_queryset(self):
        return self.model.objects.filter(test__pk=self.kwargs['test_id']).order_by('serial_number')


class ChangeUserInfoView(UpdateView):
    model = User
    fields = ['username','email', 'phone_number']
    template_name = 'educportal/change_personal_info.html'
    success_url = reverse_lazy('personal_info')

    def get_object(self, queryset=None):
         return self.request.user

educportal/templates/educportal/base.html
{% extends 'educportal/base_general.html' %}
{% load i18n %}
{% load staticfiles %}
{% load activeurl %}
{% block header %}
    {{ block.super }}
   <link href="{% static "educportal/styles/dashboard.css"%}" rel="stylesheet">
{% endblock %}
{% block header_menu %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://bootstrap-3.ru/examples/dashboard/#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
        {% activeurl %}
          <ul class="nav navbar-nav navbar-left">
            <li><a href="http://bootstrap-3.ru/examples/dashboard/#">{% trans "Главная" %}</a></li>
              {% for super_section_item in super_section_list %}
                <li><a href="{% url 'section_page' super_section_item.pk %}">{{ super_section_item.name }}</a></li>
              {% endfor %}
          </ul>
        {% endactiveurl %}
          <ul class="nav navbar-nav navbar-right">
              <li>
                  <form id='lang_en' action="{% url 'set_language' %}" method='POST' class = 'form_setlang'>{% csrf_token %}
                    <input type='hidden' name='language' value='en'/>
                    <a href='#' title='English' onclick="document.getElementById('lang_en').submit()">
                    {% trans 'Английский' %}
                    </a>
                  </form>
              </li>
            <li>
                <form id='lang_ru' action="{% url 'set_language' %}" method='POST' class = 'form_setlang'>{% csrf_token %}
                    <input type='hidden' name='language' value='ru'/>

                    <a href='#' title='Russian' onclick="document.getElementById('lang_ru').submit()">
                    {% trans 'Русский' %}
                    </a>
                </form>
              </li>
              {% if user.is_authenticated and not user.is_superuser %}

                    <li><a data-toggle="modal" href="{% url 'profile_page' %}">{{user.first_name|title}} {{user.last_name|title}}</a></li>
                    <li><a data-toggle="modal" href="{% url 'logout' %}">{% trans 'Выйти' %}</a></li>
              {% else %}
                  <li><a data-toggle="modal" href="{% url 'reg_page' %}">{% trans 'Зарегистрироваться' %}</a></li>
                  <li><a data-toggle="modal" href="{% url 'login_page' %}">{% trans 'Войти' %}</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
{% endblock %}
        {% block content %}
            {{ block.super }}
        {% endblock %}
        {% block scripts %}
            {{ block.super }}
        {% endblock %}

educportal/templates/educportal/change_personal_info.html
{% extends 'educportal/profile_page.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block header_menu %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row profile">
        {% block leftsidebar %}
            {{ block.super }}
        {% endblock %}
        {% block contentinfo %}
            <div class="col-md-9">
                <div class="profile-content">
                        <form class="form-horizontal" method="post" id="changeUserInfo-form" novalidate>
                            {% csrf_token %}
                            <div class="form-group {% if form.username.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3">{% trans 'Изменение логина:' %}</label>
                                <div class="col-xs-9">
                                    {{ form.username|add_class:'form-control'|append_attr:'placeholder:Введите новый логин' }}
                                    {% if form.username.errors %}
                                    <p class="text-danger">{{ form.username.errors.as_text }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group {% if form.email.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3">{% trans 'Изменение email:' %}</label>
                                <div class="col-xs-9">
                                {{ form.email|add_class:'form-control'|append_attr:'placeholder:Введите новый email' }}
                                {% if form.email.errors %}
                                <p class="text-danger">{{ form.email.errors.as_text }}</p>
                                {% endif %}
                                </div>
                            </div>
                            <div class="form-group {% if form.phone_number.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3 text-left">{% trans 'Изменение мобильного номера:'%}</label>
                                <div class="col-xs-9">
                                    {{ form.phone_number|add_class:'form-control'|append_attr:'placeholder:Введите новый мобильный номер' }}
                                    {% if form.phone_number.errors %}
                                        <p class="text-danger">{{ form.phone_number.errors.as_text }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-offset-3 col-xs-9">
                                <input type="submit" class="btn btn-primary" name="btn-reg" form="changeUserInfo-form" value="Сохранить изменения">
                                    <a class="btn btn-danger" href="{% url 'change_user_password' %}" role="button">{% trans 'Изменить пароль'%}</a>
                                </div>
                            </div>
                        </form>
                        {% if form.non_field_errors %}
                            {% for err in form.non_field_errors %}
                                <div class="alert alert-danger">{{ err }}</div>
                            {% endfor %}
                          {% endif %}
                </div>
            </div>
            {% endblock %}
    </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "educportal/js/jquery.maskedinput.js" %}"></script>
    <script type="text/javascript">
        $('document').ready(function()
        {
            $("#{{form.phone_number.id_for_label}}").mask('+7(999) 999-9999');
        });
    </script>
{% endblock %}

educportal/templates/educportal/change_user_password.html
{% extends 'educportal/profile_page.html' %}
{% load widget_tweaks %}
{% load staticfiles %}
{% load i18n %}
{% load activeurl %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block header_menu %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row profile">
        {% block leftsidebar %}
            {{ block.super }}
        {% endblock %}
        {% block contentinfo %}
            <div class="col-md-9">
                <div class="profile-content">
                        <form class="form-horizontal" method="post" id="changeUserPassword-form" novalidate>
                            {% csrf_token %}
                            <div class="form-group {% if form.old_password.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3">{{ form.old_password.label_tag }}</label>
                                <div class="col-xs-9">
                                    {{ form.old_password|add_class:'form-control'|append_attr:'placeholder:Введите старый пароль' }}
                                    {% if form.old_password.errors %}
                                    <p class="text-danger">{{ form.old_password.errors.as_text }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group {% if form.new_password1.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3">{{ form.new_password1.label_tag }}</label>
                                <div class="col-xs-9">
                                {{ form.new_password1|add_class:'form-control'|append_attr:'placeholder:Введите новый пароль' }}
                                {% if form.new_password1.errors %}
                                <p class="text-danger">{{ form.new_password1.errors.as_text }}</p>
                                {% endif %}
                                </div>
                            </div>
                            <div class="form-group {% if form.new_password2.errors  %}has-error{% endif %}">
                                <label class="control-label col-xs-3 text-left">{{ form.new_password2.label_tag }}</label>
                                <div class="col-xs-9">
                                    {{ form.new_password2|add_class:'form-control'|append_attr:'placeholder:Подтвердите пароль' }}
                                    {% if form.new_password2.errors %}
                                        <p class="text-danger">{{ form.new_password2.errors.as_text }}</p>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-offset-3 col-xs-9">
                                <input type="submit" class="btn btn-primary" name="btn-reg" form="changeUserPassword-form" value="Сохранить изменения">
                                </div>
                            </div>
                        </form>
                        {% if form.non_field_errors %}
                            {% for err in form.non_field_errors %}
                                <div class="alert alert-danger">{{ err }}</div>
                            {% endfor %}
                          {% endif %}
                </div>
            </div>
            {% endblock %}
    </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}

educportal/templates/educportal/extended_content.html
{% extends 'educportal/base.html' %}
{% load i18n %}
{% block header %}
    {{ block.super }}
{% endblock %}
{% block header_menu %}
    {{ block.super }}
{% endblock %}
{% block content %}
    {% block leftsidebar %}
        {% endblock %}
    {% block contentinfo %}
    {% endblock %}
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}

educportal/templates/educportal/task_item.html
{% extends 'educportal/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block header %}
    {{ block.super }}
    <title>Test task_page</title>
    <link href="{% static "educportal/styles/tasks.css"%}" rel="stylesheet">
{% endblock %}
{% block header_menu %}
    {{ block.super }}
{% endblock %}
{% block content %}
    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3 wrapper">
                {% for task_item in task %}
                    <div class="col-sm-12 col-md-12 title">
                    <h2>{{ task_item.title }}</h2>
                    </div>
                <div class="col-sm-12 col-md-12 content">
                    {% autoescape off %}{{ task_item.task_content }}{% endautoescape %}
                </div>
                <div class="col-sm-12 col-md-12 taskanswer">

                    {% for task_answer_item in task_item.taskanswer_set.all %}
                            <div class="form-check radio-pink-gap">
                            <div class = "col-sm-1 col-md-1 ">
                            <input type="radio" name="answer_group" id="{{ task_answer_item.pk }}">
                            </div>
                            <div class="col-sm-11 col-md-11">
                            <label for="{{ task_answer_item.pk }}">{% autoescape off%}{{ task_answer_item.task_answer_content }}{% endautoescape %}</label>
                            </div>
                            </div>
                    {% endfor %}
{#{{ task_item.test.pk|add:task_item.pk}}#}
                </div>
                <div class="col-sm-12 col-md-12 pagination" >
                        {% if is_paginated %}
                           {% if page_obj.has_previous %}
                               <div class="col-sm-5 col-md-5"><a  class = 'btn btn-primary' href="?page={{ page_obj.previous_page_number }}">Предыдущий</a></div>
                           {% endif %}
                            {% if page_obj.has_next %}
                            <div class="col-sm-5 col-md-5 col-md-offset-1 col-sm-offset-1 pull-right"><a id="super_id" class = 'btn btn-primary pull-right next' href="?page={{ page_obj.next_page_number }}">Следующий</a></div>
                            {% else %}
                                <div class="col-sm-5 col-md-5 col-md-offset-1 col-sm-offset-1 pull-right"><a href="{% url 'profile_page' %}"class = 'btn btn-danger pull-right' href="">Закончить тест</a></div>
                            {% endif %}
                        {% endif %}
                </div>
              {% endfor %}
          </div>
      </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        {#$('document').ready(function() {#}
        {#        $( "#super_id" ).click(function() {#}
        {#            alert($('input[type=radio][name=answer_group]:checked').attr('id'))#}
        {#        })#}
        {#});#}
    </script>
{% endblock %}

educportal/templates/educportal/themes_list.html
{% extends 'educportal/section_list.html' %}
{% load i18n %}
{% block header %}
    {{ block.super }}
    <title>{{ title_page }}</title>
{% endblock %}
{% block header_menu %}
    {{ block.super }}
{% endblock %}
{% block content %}
<div class="container-fluid">
      <div class="row">
      {% block leftsidebar %}
            {{ block.super }}
      {% endblock %}
        {% block contentinfo %}
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
             <ul class="nav nav-sidebar">
                {% for themes_item in themes_list %}
                    <li><a href="{{ themes_item.get_absolute_url|safe }} ">{{ themes_item.name }}</a></li>
                {% endfor %}
            </ul>
            </div>
        {% endblock %}
      </div>
</div>
    {% endblock %}
{% block scripts %}
            {{ block.super }}
{% endblock %}